export default {
  GET_AUTHORS: "GET_AUTHORS",
  SEARCH_AUTHORS: "SEARCH_AUTHORS",
  CLEAR_AUTHORS: "CLEAR_AUTHORS",

  GET_AUTHOR: "GET_AUTHOR",
  CHANGE_AUTHOR: "CHANGE_AUTHOR",
  SAVE_AUTHOR: "SAVE_AUTHOR",
  DELETE_AUTHOR: "DELETE_AUTHOR",
  CLEAR_AUTHOR: "CLEAR_AUTHOR",

  GET_COURSES: "GET_COURSES",
  SEARCH_COURSES: "SEARCH_COURSES",
  CLEAR_COURSES: "CLEAR_COURSES",

  GET_COURSE: "GET_COURSE",
  CHANGE_COURSE: "CHANGE_COURSE",
  SAVE_COURSE: "SAVE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  CLEAR_COURSE: "CLEAR_COURSE",

  GET_COURSES_BY_AUTHOR_NAME: "GET_COURSES_BY_AUTHOR_NAME",
  CLEAR_COURSES_BY_AUTHOR_NAME: "CLEAR_COURSES_BY_AUTHOR_NAME",

  SET_API_ERROR: "SET_API_ERROR",
  CLEAR_API_ERROR: "CLEAR_API_ERROR",

  ADD_ALERT: "ADD_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT"
};
